apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-jfvilas
  namespace: dev
spec:
  ingressClassName: nginx
  # tls:
  # - hosts:
  #   - www.jfvilas.com
  #   secretName: www.jfvilas.com.tls
  rules:
  - host: localhost
    http:
      paths:
        # access to authrizator API (not needed by the console, but useful if you to manage authorizator externally)
        - path: /obk-authorizator/dev/ja-jfvilas
          pathType: Prefix
          backend:
            service:
              name: obk-authorizator-ja-jfvilas-svc
              port:
                number: 3882
        - path: /demo
          pathType: Prefix
          backend:
            service:
              name: demo-nginx-svc
              port:
                number: 81
        - path: /app1
          pathType: Prefix
          backend:
            service:
              name: app1-nginx-svc
              port:
                number: 81
        - path: /app2
          pathType: Prefix
          backend:
            service:
              name: app2-nginx-svc
              port:
                number: 81
